# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/ascon_const.xdc

# Block Designs: bd/design_ascon/design_ascon.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_ascon || ORIG_REF_NAME==design_ascon} -quiet] -quiet

# IP: bd/design_ascon/ip/design_ascon_processing_system7_0_3/design_ascon_processing_system7_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_ascon_processing_system7_0_3 || ORIG_REF_NAME==design_ascon_processing_system7_0_3} -quiet] -quiet

# IP: bd/design_ascon/ip/design_ascon_rst_ps7_0_50M_4/design_ascon_rst_ps7_0_50M_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_ascon_rst_ps7_0_50M_4 || ORIG_REF_NAME==design_ascon_rst_ps7_0_50M_4} -quiet] -quiet

# IP: bd/design_ascon/ip/design_ascon_xlconcat_0_0/design_ascon_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_ascon_xlconcat_0_0 || ORIG_REF_NAME==design_ascon_xlconcat_0_0} -quiet] -quiet

# IP: bd/design_ascon/ip/design_ascon_xlconcat_0_1/design_ascon_xlconcat_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_ascon_xlconcat_0_1 || ORIG_REF_NAME==design_ascon_xlconcat_0_1} -quiet] -quiet

# IP: bd/design_ascon/ip/design_ascon_xlconcat_1_0/design_ascon_xlconcat_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_ascon_xlconcat_1_0 || ORIG_REF_NAME==design_ascon_xlconcat_1_0} -quiet] -quiet

# IP: bd/design_ascon/ip/design_ascon_xlslice_0_0/design_ascon_xlslice_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_ascon_xlslice_0_0 || ORIG_REF_NAME==design_ascon_xlslice_0_0} -quiet] -quiet

# IP: bd/design_ascon/ip/design_ascon_xlslice_0_1/design_ascon_xlslice_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_ascon_xlslice_0_1 || ORIG_REF_NAME==design_ascon_xlslice_0_1} -quiet] -quiet

# IP: bd/design_ascon/ip/design_ascon_xlslice_0_2/design_ascon_xlslice_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_ascon_xlslice_0_2 || ORIG_REF_NAME==design_ascon_xlslice_0_2} -quiet] -quiet

# IP: bd/design_ascon/ip/design_ascon_xlslice_0_3/design_ascon_xlslice_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_ascon_xlslice_0_3 || ORIG_REF_NAME==design_ascon_xlslice_0_3} -quiet] -quiet

# IP: bd/design_ascon/ip/design_ascon_axi_gpio_0_0/design_ascon_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_ascon_axi_gpio_0_0 || ORIG_REF_NAME==design_ascon_axi_gpio_0_0} -quiet] -quiet

# IP: bd/design_ascon/ip/design_ascon_axi_gpio_0_1/design_ascon_axi_gpio_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_ascon_axi_gpio_0_1 || ORIG_REF_NAME==design_ascon_axi_gpio_0_1} -quiet] -quiet

# IP: bd/design_ascon/ip/design_ascon_axi_gpio_0_2/design_ascon_axi_gpio_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_ascon_axi_gpio_0_2 || ORIG_REF_NAME==design_ascon_axi_gpio_0_2} -quiet] -quiet

# IP: bd/design_ascon/ip/design_ascon_axi_gpio_0_3/design_ascon_axi_gpio_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_ascon_axi_gpio_0_3 || ORIG_REF_NAME==design_ascon_axi_gpio_0_3} -quiet] -quiet

# IP: bd/design_ascon/ip/design_ascon_axi_gpio_13_0/design_ascon_axi_gpio_13_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_ascon_axi_gpio_13_0 || ORIG_REF_NAME==design_ascon_axi_gpio_13_0} -quiet] -quiet

# IP: bd/design_ascon/ip/design_ascon_axi_gpio_13_1/design_ascon_axi_gpio_13_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_ascon_axi_gpio_13_1 || ORIG_REF_NAME==design_ascon_axi_gpio_13_1} -quiet] -quiet

# IP: bd/design_ascon/ip/design_ascon_axi_gpio_13_2/design_ascon_axi_gpio_13_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_ascon_axi_gpio_13_2 || ORIG_REF_NAME==design_ascon_axi_gpio_13_2} -quiet] -quiet

# IP: bd/design_ascon/ip/design_ascon_axi_gpio_13_3/design_ascon_axi_gpio_13_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_ascon_axi_gpio_13_3 || ORIG_REF_NAME==design_ascon_axi_gpio_13_3} -quiet] -quiet

# IP: bd/design_ascon/ip/design_ascon_axi_gpio_3_0/design_ascon_axi_gpio_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_ascon_axi_gpio_3_0 || ORIG_REF_NAME==design_ascon_axi_gpio_3_0} -quiet] -quiet

# IP: bd/design_ascon/ip/design_ascon_axi_gpio_3_1/design_ascon_axi_gpio_3_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_ascon_axi_gpio_3_1 || ORIG_REF_NAME==design_ascon_axi_gpio_3_1} -quiet] -quiet

# IP: bd/design_ascon/ip/design_ascon_axi_gpio_3_2/design_ascon_axi_gpio_3_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_ascon_axi_gpio_3_2 || ORIG_REF_NAME==design_ascon_axi_gpio_3_2} -quiet] -quiet

# IP: bd/design_ascon/ip/design_ascon_axi_gpio_3_3/design_ascon_axi_gpio_3_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_ascon_axi_gpio_3_3 || ORIG_REF_NAME==design_ascon_axi_gpio_3_3} -quiet] -quiet

# IP: bd/design_ascon/ip/design_ascon_axi_gpio_4_0/design_ascon_axi_gpio_4_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_ascon_axi_gpio_4_0 || ORIG_REF_NAME==design_ascon_axi_gpio_4_0} -quiet] -quiet

# IP: bd/design_ascon/ip/design_ascon_axi_gpio_8_0/design_ascon_axi_gpio_8_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_ascon_axi_gpio_8_0 || ORIG_REF_NAME==design_ascon_axi_gpio_8_0} -quiet] -quiet

# IP: bd/design_ascon/ip/design_ascon_axi_gpio_8_1/design_ascon_axi_gpio_8_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_ascon_axi_gpio_8_1 || ORIG_REF_NAME==design_ascon_axi_gpio_8_1} -quiet] -quiet

# IP: bd/design_ascon/ip/design_ascon_axi_gpio_8_2/design_ascon_axi_gpio_8_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_ascon_axi_gpio_8_2 || ORIG_REF_NAME==design_ascon_axi_gpio_8_2} -quiet] -quiet

# IP: bd/design_ascon/ip/design_ascon_axi_gpio_8_3/design_ascon_axi_gpio_8_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_ascon_axi_gpio_8_3 || ORIG_REF_NAME==design_ascon_axi_gpio_8_3} -quiet] -quiet

# IP: bd/design_ascon/ip/design_ascon_xbar_0/design_ascon_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_ascon_xbar_0 || ORIG_REF_NAME==design_ascon_xbar_0} -quiet] -quiet

# IP: bd/design_ascon/ip/design_ascon_tier2_xbar_0_0/design_ascon_tier2_xbar_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_ascon_tier2_xbar_0_0 || ORIG_REF_NAME==design_ascon_tier2_xbar_0_0} -quiet] -quiet

# IP: bd/design_ascon/ip/design_ascon_tier2_xbar_1_0/design_ascon_tier2_xbar_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_ascon_tier2_xbar_1_0 || ORIG_REF_NAME==design_ascon_tier2_xbar_1_0} -quiet] -quiet

# IP: bd/design_ascon/ip/design_ascon_tier2_xbar_2_0/design_ascon_tier2_xbar_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_ascon_tier2_xbar_2_0 || ORIG_REF_NAME==design_ascon_tier2_xbar_2_0} -quiet] -quiet

# IP: bd/design_ascon/ip/design_ascon_auto_pc_0/design_ascon_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_ascon_auto_pc_0 || ORIG_REF_NAME==design_ascon_auto_pc_0} -quiet] -quiet

# IP: bd/design_ascon/ip/design_ascon_ps7_0_axi_periph_0/design_ascon_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_ascon_ps7_0_axi_periph_0 || ORIG_REF_NAME==design_ascon_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/design_ascon/ip/design_ascon_ascon_core_0_2/design_ascon_ascon_core_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_ascon_ascon_core_0_2 || ORIG_REF_NAME==design_ascon_ascon_core_0_2} -quiet] -quiet

# XDC: c:/Users/david/Documents/ASCON-project/project_ascon.gen/sources_1/bd/design_ascon/design_ascon_ooc.xdc
