# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/david/Documents/ASCON-project/project_ascon.srcs/sources_1/bd/design_ascon/ip/design_ascon_ascon_core_0_2/design_ascon_ascon_core_0_2.xci
# IP: The module: 'design_ascon_ascon_core_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/david/Documents/ASCON-project/project_ascon.gen/sources_1/bd/design_ascon/ip/design_ascon_ascon_core_0_2/constrs_1/new/ascon_top.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_ascon_ascon_core_0_2'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/david/Documents/ASCON-project/project_ascon.srcs/sources_1/bd/design_ascon/ip/design_ascon_ascon_core_0_2/design_ascon_ascon_core_0_2.xci
# IP: The module: 'design_ascon_ascon_core_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/david/Documents/ASCON-project/project_ascon.gen/sources_1/bd/design_ascon/ip/design_ascon_ascon_core_0_2/constrs_1/new/ascon_top.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_ascon_ascon_core_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
