# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/david/Documents/ASCON-project/project_ascon.srcs/sources_1/bd/design_ascon/ip/design_ascon_axi_gpio_4_0/design_ascon_axi_gpio_4_0.xci
# IP: The module: 'design_ascon_axi_gpio_4_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/david/Documents/ASCON-project/project_ascon.gen/sources_1/bd/design_ascon/ip/design_ascon_axi_gpio_4_0/design_ascon_axi_gpio_4_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_ascon_axi_gpio_4_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/david/Documents/ASCON-project/project_ascon.gen/sources_1/bd/design_ascon/ip/design_ascon_axi_gpio_4_0/design_ascon_axi_gpio_4_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_ascon_axi_gpio_4_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/david/Documents/ASCON-project/project_ascon.gen/sources_1/bd/design_ascon/ip/design_ascon_axi_gpio_4_0/design_ascon_axi_gpio_4_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_ascon_axi_gpio_4_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/david/Documents/ASCON-project/project_ascon.srcs/sources_1/bd/design_ascon/ip/design_ascon_axi_gpio_4_0/design_ascon_axi_gpio_4_0.xci
# IP: The module: 'design_ascon_axi_gpio_4_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/david/Documents/ASCON-project/project_ascon.gen/sources_1/bd/design_ascon/ip/design_ascon_axi_gpio_4_0/design_ascon_axi_gpio_4_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_ascon_axi_gpio_4_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/david/Documents/ASCON-project/project_ascon.gen/sources_1/bd/design_ascon/ip/design_ascon_axi_gpio_4_0/design_ascon_axi_gpio_4_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_ascon_axi_gpio_4_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/david/Documents/ASCON-project/project_ascon.gen/sources_1/bd/design_ascon/ip/design_ascon_axi_gpio_4_0/design_ascon_axi_gpio_4_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_ascon_axi_gpio_4_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
